// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: feido-proto/feido-database.proto

package feido_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ICheckitQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Note: first 3 elements of data group 1 (but in different order)
	TravelDocumentNumber []byte `protobuf:"bytes,1,req,name=travelDocumentNumber" json:"travelDocumentNumber,omitempty"` // 9B ("Document number")
	CountryOfIssuance    []byte `protobuf:"bytes,2,req,name=countryOfIssuance" json:"countryOfIssuance,omitempty"`       // 3B ("Issuing State or organization")
	DocumentType         []byte `protobuf:"bytes,3,req,name=documentType" json:"documentType,omitempty"`                 // 2B ("Document code")
}

func (x *ICheckitQuery) Reset() {
	*x = ICheckitQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feido_proto_feido_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ICheckitQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICheckitQuery) ProtoMessage() {}

func (x *ICheckitQuery) ProtoReflect() protoreflect.Message {
	mi := &file_feido_proto_feido_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICheckitQuery.ProtoReflect.Descriptor instead.
func (*ICheckitQuery) Descriptor() ([]byte, []int) {
	return file_feido_proto_feido_database_proto_rawDescGZIP(), []int{0}
}

func (x *ICheckitQuery) GetTravelDocumentNumber() []byte {
	if x != nil {
		return x.TravelDocumentNumber
	}
	return nil
}

func (x *ICheckitQuery) GetCountryOfIssuance() []byte {
	if x != nil {
		return x.CountryOfIssuance
	}
	return nil
}

func (x *ICheckitQuery) GetDocumentType() []byte {
	if x != nil {
		return x.DocumentType
	}
	return nil
}

type ICheckitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDbHit *bool `protobuf:"varint,1,req,name=isDbHit" json:"isDbHit,omitempty"` // true: eID revoked/stolen
}

func (x *ICheckitResponse) Reset() {
	*x = ICheckitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feido_proto_feido_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ICheckitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICheckitResponse) ProtoMessage() {}

func (x *ICheckitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feido_proto_feido_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICheckitResponse.ProtoReflect.Descriptor instead.
func (*ICheckitResponse) Descriptor() ([]byte, []int) {
	return file_feido_proto_feido_database_proto_rawDescGZIP(), []int{1}
}

func (x *ICheckitResponse) GetIsDbHit() bool {
	if x != nil && x.IsDbHit != nil {
		return *x.IsDbHit
	}
	return false
}

var File_feido_proto_feido_database_proto protoreflect.FileDescriptor

var file_feido_proto_feido_database_proto_rawDesc = []byte{
	0x0a, 0x20, 0x66, 0x65, 0x69, 0x64, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65,
	0x69, 0x64, 0x6f, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x66, 0x65, 0x69, 0x64, 0x6f, 0x5f, 0x64, 0x62, 0x22, 0x95, 0x01, 0x0a,
	0x0d, 0x49, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x32,
	0x0a, 0x14, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x14, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4f, 0x66, 0x49,
	0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x11, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4f, 0x66, 0x49, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x49, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x44, 0x62,
	0x48, 0x69, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44, 0x62, 0x48,
	0x69, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x66, 0x65, 0x69, 0x64, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f,
}

var (
	file_feido_proto_feido_database_proto_rawDescOnce sync.Once
	file_feido_proto_feido_database_proto_rawDescData = file_feido_proto_feido_database_proto_rawDesc
)

func file_feido_proto_feido_database_proto_rawDescGZIP() []byte {
	file_feido_proto_feido_database_proto_rawDescOnce.Do(func() {
		file_feido_proto_feido_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_feido_proto_feido_database_proto_rawDescData)
	})
	return file_feido_proto_feido_database_proto_rawDescData
}

var file_feido_proto_feido_database_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feido_proto_feido_database_proto_goTypes = []interface{}{
	(*ICheckitQuery)(nil),    // 0: feido_db.ICheckitQuery
	(*ICheckitResponse)(nil), // 1: feido_db.ICheckitResponse
}
var file_feido_proto_feido_database_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feido_proto_feido_database_proto_init() }
func file_feido_proto_feido_database_proto_init() {
	if File_feido_proto_feido_database_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feido_proto_feido_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ICheckitQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feido_proto_feido_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ICheckitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feido_proto_feido_database_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feido_proto_feido_database_proto_goTypes,
		DependencyIndexes: file_feido_proto_feido_database_proto_depIdxs,
		MessageInfos:      file_feido_proto_feido_database_proto_msgTypes,
	}.Build()
	File_feido_proto_feido_database_proto = out.File
	file_feido_proto_feido_database_proto_rawDesc = nil
	file_feido_proto_feido_database_proto_goTypes = nil
	file_feido_proto_feido_database_proto_depIdxs = nil
}
